### ISSUE TITLE
Add 'deltarpm' to minimize size of downloads on 'yum update'

### ISSUE THREAD

**Issue by jeffwidman** [geerlingguy/packer-centos-7#7]
Be convenient if the 'deltarpm' package were installed by default. 

I'm using this with vagrant, and first thing I do when I create the box is 'yum update'... with deltarpm installed, it saves ~37mb of bandwidth. 

Not a big deal as obviously I can instead do 'yum install deltarpm', 'yum update' but it would be handy.

**Comment by geerlingguy** [comment]
@jeffwidman - I'd prefer to stick as closely to the built-in minimal packages, plus the barebones of what's needed for Vagrant to work, so I'm going to leave this up to downstream users of the base box to install. Otherwise you can fork it and add it as part of your build. It won't be in the `geerlingguy/*` boxes, though, sorry!

**Comment by jeffwidman** [comment]
No problem, I understand your reasoning.
